# Generated by Django 2.2.6 on 2019-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_map', '0002_auto_20191026_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_info',
            name='data',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='address_info',
            name='index',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='address_info',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='address_info',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weights',
            name='index1',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weights',
            name='index2',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weights',
            name='state',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='weights',
            name='weight',
            field=models.IntegerField(db_index=True),
        ),
    ]
