# Generated by Django 2.2.6 on 2019-10-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_map', '0003_auto_20191027_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_info',
            name='data',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address_info',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='address_info',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
